version = 1
title = 'dice'

[[modules]]
plugin = 'source.svelte'
data.contents = '''
<script>
  import Die from './Die.svelte';
  import Dice from './Dice.svelte';

  function genRandomDice(n) {
    return new Array(n).fill(1).map(_ => Math.floor(Math.random() * 6) + 1);
  }
  function genRandomDiceSets(a, n) {
    return new Array(a).fill(1).map(_ => (genRandomDice(n)));
  }

  const NUM_SETS = 40;
</script>

<div style="font-size:xx-large;user-select:none;line-height:1;height:1em;overflow:hidden;position:relative">
  <div>
    {#each genRandomDiceSets(NUM_SETS, 2) as digits, i}
      <details style="height:1em">
        <summary style="display:flex;gap:4px;cursor:pointer;animation:{0.2 * NUM_SETS}s steps({NUM_SETS},jump-start) infinite spin;transform:translateY(-{NUM_SETS}em);height:{NUM_SETS}em">
          {#each genRandomDice(2) as digit}
            <div>
              <Die digit={digit}/>
            </div>
          {/each}
        </summary>
        <div style="position:absolute;inset:0;background-color:#fff;color:#000;z-index:999">
          <Dice digits={digits}/>
        </div>
      </details>
    {/each}
  </div>
</div>'''
sends = [1]

[[modules]]
plugin = 'transform.style-inliner'
data.mode = 'attr'
sends = ['output']

[[modules]]
plugin = 'source.svelte-component'
data.name = 'Dice'
data.contents = '''
<script>
  import DieRolling from './DieRolling.svelte';
  export let digits;

  function appendRandom(n, amt) {
    return [...(new Array(amt).fill(1).map(_ => Math.floor(Math.random() * 6) + 1)), n];
  }
</script>

<div style="display:flex;gap:4px">
  {#each digits as digit, i}
    <div style="height:1em;overflow:hidden">
      <DieRolling digits={appendRandom(digit, 6 * (i + 1))}/>
    </div>
  {/each}
</div>'''
namedSends = { '0' = ['Dice'] }

[[modules]]
plugin = 'source.svelte-component'
data.name = 'DieRolling'
data.contents = '''
<script>
  import Die from './Die.svelte';
  export let digits;
</script>

<div style="display:flex;flex-direction:column;animation:{0.08 * digits.length}s steps({digits.length - 1},jump-start) 1 spin;transform:translateY(-{digits.length - 1}em);">
  {#each digits as digit, i}
    <div>
      <Die digit={digit}/>
    </div>
  {/each}
</div>'''
namedSends = { '0' = ['DieRolling'] }

[[modules]]
plugin = 'source.svelte-component'
data.name = 'Die'
data.contents = '''
<script>
  export let digit;
</script>

{#if digit === 1}
⚀
{:else if digit === 2}
⚁
{:else if digit === 3}
⚂
{:else if digit === 4}
⚃
{:else if digit === 5}
⚄
{:else if digit === 6}
⚅
{/if}'''
namedSends = { '0' = ['Die'] }
