version = 1
title = 'peep the horror'

[[modules]]
plugin = 'source.svelte'
data.contents = '''
<style>
  .container {
    position: relative;
    width: 600px;
    height: 400px;
  }
  .actual-container {
    width: 100%;
    height: 100%;
    overflow: hidden;
  }
  .mult {
    mix-blend-mode: multiply;
  }
  .add {
    mix-blend-mode: screen;
  }
  .segment {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
  }
  .segment-size {
    width: 100%;
    height: 100%;
  }
  .slide {
    position: relative;
    animation: 4s spin linear infinite;
    transform: translate(64px, 0px);
    left: -64px;
    width: calc(100% + 64px);
    height: 100%;
  }
  .slowspin {
    animation: 20s spin linear infinite;
  }
  .slowspin-2 {
    animation: 28s spin linear infinite;
    animation-delay: 2s;
    animation-direction: reverse;
  }
  .unslowspin {
    animation: 20s spin linear infinite;
    animation-direction: reverse;
  }
  .unslowspin-2 {
    animation: 28s spin linear infinite;
    animation-delay: 2s;
  }
  .slowscale {
    animation: 4s spin ease-in-out infinite;
    animation-direction: alternate;
    transform: scale(1.4, 1.4);
  }
  .slowscale-2 {
    animation: 5.2s spin ease-in-out infinite;
    animation-direction: alternate;
    transform: scale(1.4, 1.4);
  }
  .scale {
    transform: scale(1.8, 1.8);
  }
  .rotate {
    transform: rotate(55deg);
  }
  .offset-1 {
    transform: translate(0px, 50px);
  }
  .offset-2 {
    transform: translate(0px, -50px);
  }

  .opacity {
    opacity: 0.5;
  }
</style>

<script>
  import grad1 from './grad1';
  import grad2 from './grad2';
  import grad3 from './grad3';
  import grad5 from './grad5';
</script>

<div class="container-actual">
<div style="position: relative; margin: auto; height: 100%; width:100%; background-color: white; filter: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogICAgPGRlZnM+CiAgICAgICAgPGZpbHRlciBpZD0idGhyZXNob2xkIiBjb2xvci1pbnRlcnBvbGF0aW9uLWZpbHRlcnM9InNSR0IiPgogICAgICAgICAgICA8ZmVDb2xvck1hdHJpeCB0eXBlPSJzYXR1cmF0ZSIgdmFsdWVzPSIwIi8+CiAgICAgICAgICAgIDxmZUNvbXBvbmVudFRyYW5zZmVyPgogICAgICAgICAgICAgICAgPGZlRnVuY1IgdHlwZT0iZGlzY3JldGUiIHRhYmxlVmFsdWVzPSIgMCAxIi8+CiAgICAgICAgICAgICAgICA8ZmVGdW5jRyB0eXBlPSJkaXNjcmV0ZSIgdGFibGVWYWx1ZXM9IiAwIDEiLz4KICAgICAgICAgICAgICAgIDxmZUZ1bmNCIHR5cGU9ImRpc2NyZXRlIiB0YWJsZVZhbHVlcz0iIDAgMSIvPgogICAgICAgICAgICA8L2ZlQ29tcG9uZW50VHJhbnNmZXI+CiAgICAgICAgPC9maWx0ZXI+CiAgICA8L2RlZnM+Cjwvc3ZnPg==#threshold');">
  <div style="position: absolute; top: 0px; left: 0px; z-index: 100; width: 100%; height: 100%; image-rendering: pixelated; mix-blend-mode: overlay; background: rgba(0, 0, 0, 0) url('{grad5}') repeat scroll left top; pointer-events: none;">
  </div>


<div class="container">
  <div class="segment mult">
    <div class="segment-size scale">
      <div class="segment-size slowscale">
        <div class="segment-size slowspin">
          <div class="segment-size slide" style="background-image: url('{grad1}')">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment add">
    <div class="segment-size offset-1">
      <div class="segment-size slowspin">
        <div class="segment-size scale">
          <div class="segment-size offset-2">
            <div class="segment-size unslowspin">
              <div class="segment-size" style="background-image: url('{grad2}'); background-size: 25%">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment mult">
    <div class="segment-size scale">
      <div class="segment-size slowscale-2">
        <div class="segment-size slowspin-2">
          <div class="segment-size slide" style="background-image: url('{grad1}')">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment mult">
    <div class="segment-size scale">
      <div class="segment-size slowscale">
        <div class="segment-size unslowspin-2">
          <div class="segment-size slide" style="background-image: url('{grad1}')">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment add">
    <div class="segment-size scale">
      <div class="segment-size rotate">
        <div class="segment-size slowscale-2">
          <div class="segment-size slowspin">
            <div class="segment-size slide" style="background-image: url('{grad1}')">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment add">
    <div class="segment-size offset-1">
      <div class="segment-size slowspin-2">
        <div class="segment-size scale">
          <div class="segment-size offset-2">
            <div class="segment-size unslowspin-2">
              <div class="segment-size" style="background-image: url('{grad2}'); background-size: 25%">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment mult opacity">
    <div class="segment-size scale">
      <div class="segment-size slowscale-2">
        <div class="segment-size unslowspin-2">
          <div class="segment-size rotate">
            <div class="segment-size slide" style="background-image: url('{grad1}')">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment mult opacity">
    <div class="segment-size scale">
      <div class="segment-size slowscale">
        <div class="segment-size slowspin">
          <div class="segment-size scale">
            <div class="segment-size slide" style="background-image: url('{grad1}')">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="segment mult opacity">
    <div class="segment-size rotate">
      <div class="segment-size slowscale-2">
        <div class="segment-size slowspin-2">
          <div class="segment-size scale">
            <div class="segment-size slide" style="background-image: url('{grad1}')">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
</div>
<div class="segment mult" style="background: linear-gradient(to bottom, #f00 0%, #f39 100%); width: 100%; height: 100%;">
</div>
'''
sends = [1]

[[modules]]
plugin = 'transform.style-inliner'
data.mode = 'attr'
sends = ['output']

[[modules]]
plugin = 'source.file-data-url'
data.url = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABcmlDQ1BpY2MAACiRdZE9S8NQFIbftopiWzroIOoQsIpDC0VBHLUOXYqUWsGqS3KbtEKShpsUKa6Ci0PBQXTxa/Af6Cq4KgiCIog4+QP8WqTEc5tCi7Qn3JyH9573cO+5gD+tM8PuSQCG6fBsKimt5tekvncEEYYPoxiXmW0tZDJpdI2fR6qkeIiLXt3rOkawoNoM8PUTzzKLO8TzxOktxxK8RzzESnKB+IQ4xumAxLdCVzx+E1z0+Eswz2UXAb/oKRXbWGljVuIG8RRx1NArrHkecZOQaq4sUx6hNQYbWaSQhAQFFWxCh4M4ZZNm1tmXaPiWUCYPo7+FKjg5iiiRN0ZqhbqqlDXSVfp0VMXc/8/T1mamve6hJND76rqfE0DfPlCvue7vqevWz4DAC3BttvxlmtPcN+m1lhY9BiI7wOVNS1MOgKtdYPjZkrnckAK0/JoGfFwA4TwweA8MrHuzau7j/AnIbdMT3QGHR8Ak1Uc2/gDJnmfx2BoHJQAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAIpJREFUeNrt0DEKwCAQBMBLsND/P9YrhKQ3BqyTWdhm2WqOiLhqrTG3tRarfW4pZfv79svMR3vvy331G2Nsf+ftjJ8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8ITfdP16X4RNQzQAAAABJRU5ErkJggg=='
namedSends = { '0' = ['grad1'] }

[[modules]]
plugin = 'source.file-data-url'
data.url = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABcmlDQ1BpY2MAACiRdZE9S8NQFIbftopiWzroIOoQsIpDC0VBHLUOXYqUWsGqS3KbtEKShpsUKa6Ci0PBQXTxa/Af6Cq4KgiCIog4+QP8WqTEc5tCi7Qn3JyH9573cO+5gD+tM8PuSQCG6fBsKimt5tekvncEEYYPoxiXmW0tZDJpdI2fR6qkeIiLXt3rOkawoNoM8PUTzzKLO8TzxOktxxK8RzzESnKB+IQ4xumAxLdCVzx+E1z0+Eswz2UXAb/oKRXbWGljVuIG8RRx1NArrHkecZOQaq4sUx6hNQYbWaSQhAQFFWxCh4M4ZZNm1tmXaPiWUCYPo7+FKjg5iiiRN0ZqhbqqlDXSVfp0VMXc/8/T1mamve6hJND76rqfE0DfPlCvue7vqevWz4DAC3BttvxlmtPcN+m1lhY9BiI7wOVNS1MOgKtdYPjZkrnckAK0/JoGfFwA4TwweA8MrHuzau7j/AnIbdMT3QGHR8Ak1Uc2/gDJnmfx2BoHJQAAAAlwSFlzAAAuIwAALiMBeKU/dgAABNNJREFUeNrtW1tuIzEMSwwfob3//dqeoVnMAl5oGZKSPY8usJmfTNx0xqQo2Zbl++12e9z+46tf8ZLW2l/f397e5G+/vr7++v79/X1q3+5nKCACjmDf39/Lz/j8/KSkHE3IoQQM4AN0BIxWZypA68fvg5DRdhQRhxAQgQ/QEaC6r7gBu9/IOIqIXQQ44Ph5hAvg5xFELBOwgUfgCJqpYTYIRrBIAhKxQkLfCz6CjsCZ7CvyH79BIrZ2bGPkzZLQV4BHkAq4cwXmElHyETACj98VKTNE9L2Sd0qojAasfYDa/m8jhpGRKaJKQl+RfATI2rIYUHWD2QtJqZDQV8ArN1AxgPk0Sp6NEkhs1fozSugVVhEokzy2xw6oWZ0aAcYztv9j72LPcKR8fHysEYBTWqUEBj4Cx/GbqSBaf/h7/B0LsBn40bbhUCroM0MdWpxJHoHjOK5UoKwfyYhEuDgx3oUGYST0Gb/HEUBZnQFXKmBEqHWCMgQGPjXjZCRIBSi/V/N6BL+iAmd9N1psn8zq2SyTEhAnOyoIRjUo8GyqmgXCCFjdKxLcOgNHj6iCnlmf+T3zeQY+AmcqcAEvcwk1XLJ4wCZZlIBofWbpFfBKBY/H4ylo3e/3MuiMhDibRDKjCrqyPgs2uFipgI/AI2h2xb+P/58hYvQTrY7xIRqiZ76v1DADPgPuyKjO+FQ8iKMCiwXdSUlF/ejXZ4BHIiokxAUTGxWiKmIc6mouznwfrZ+NAnvBV0hAo6AKYixg9y3L26lFDYvyZ4BHEjC4qtGmiqupNLaa6irrx+9Hg1dKcH3J0nUDd8vW4WoMVda/4lIqYP3MMDXn/2oIYvn6s63vVJDNMNnoMO5bJRujVKA6cpUKsj5lWP4QUPlhdfPiymumDwpjmwHNrKymt2e7gQOeqZHGALcsnn3BT12VPOPT6vcMOV4t/z3XYQSsprJ/+n3tDFn91LXirm1GVuwF0RJjPX/2Fd+Tbbll7tOyLG1FglfLf6UPCmOr/jB76dVuofYbXfqLtTXmK5jKdsxjR852g+357v3O+gxjW7U+27K6SgVqk3ZFBb8JiGliV4GhcoZXqYBZX/VF7U1gxVnL5tUqwaA2SUfb0SQM8G6L3iVw1H3HMZPl0LJ0k/O9I9YHDHymREyWMP9/IoBlTjHvplLPbvjZQ4IDr6yPlmZu/UTA5g8uheySC9V5+wwRw4Uq4F3KXqXO5MaI20TA1PNM1HY7Q2qGp3ajnQrQ2i5/+URAVAGzOrbNzgAHEagOfA4ruqyCZ76PbpBujsZOutKTCgkIGp/H6oJmVYDg0fouaftEgIoFbkbotq6x5M2RymZ4qigLRwEG3vm+VUC2jGT79lkhA9b5uSDqSm5VZQpGfSRE4aEEDBVkVh1EqeqR2WquGRW42R4DP1UjxEhQNbwsJrCaPmZ9VSWmVKBKcrKo72oFbZkcWyNkEdzV9Kk5RaYCVXvIgh1GfcQxRYCzOJayMJdgRDDrV0YEJXlVlMWC4BIBLh44RUSC2HBZnUOwcju1I83adtcKMxJWanhmgLuzQk7yKwcopk6MXHleAEHjp5K8Gu8PIQCJOOPEiAKfJTlWj80sHZmpxAUWJLP8AQu6Z58Zep0au73ODb5Ojr7ODp+dx/+XT4//AlKNJdshlQ5LAAAAAElFTkSuQmCC'
namedSends = { '0' = ['grad2'] }

[[modules]]
plugin = 'source.file-data-url'
data.url = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABb2lDQ1BpY2MAACiRdZE7SwNBFIW/JErEBym0ELHYIoqFAVEQS42FTZAQFYzaZNdsImTjsrtBxFawsQhYiDa+Cv+BtoKtgiAogoiVP8BXI7LecYUE0Vlm78eZOZeZMxBOlQzLbRgAq+w5mYmkNpud06JPtNBGmCiJnOHaY+l0in/H+w0hVa8Tqtf/+/4cLYt514BQk/CwYTue8KhwasWzFW8KdxjF3KLwvnC/IwcUvlC6HvCj4kLAr4qd6cw4hFVPrVDHeh0bRccS7hOOW6WK8XMedZPWfHlmSmqXzG5cMkyQREOnwhIlPBJSy5LZ376Bb98ky+Ix5G+ziiOOAkXx9otaka55qaboeflKrKrcf+fpmkODQffWJDQ++P5LD0S34LPq+x8Hvv95CJF7OCvX/MuS08ib6NWaFt+D2DqcnNc0fRtON6Dzzs45uW8pIjNsmvB8DG1ZaL+C5vkgq591jm5hek2e6BJ2dqFX9scWvgC2CWfolMhqzAAAAAlwSFlzAAAuIwAALiMBeKU/dgAAA1dJREFUeNrtWwmu6jAMLFGPAHeA+x8GzgCcAb7Ml6V5IztbG1IgkaouLPGMx06aurtpmp7TD7cw/XgbBAwCBgG/3ebcL+52u9d+v9//uX44HLqDuN1uf87v9/tr/3w+lxMgwAW0AFXwSIJHABO1RlNgMQL0O7KX67KPETGnwJ9OpxcYjwSLgBbgYyQoAQxe7JDj8/nskhAlQIEzCfiZRcI7CRCgx+PxdV0/Y/ByzGGSJEC8rx5H8NKZgmag7IFSKafIQ6JZiV6farcXCkkFKFAFj8CxUwSfA7S0SZ+Xy8UEj47iPhV8cQ7AThg8JhgGjjJcgwgr4Vre5xzFfXthMOd2rucMXje9lqOCWHjEkqoogB1jhQyDjYXVnOMBTH4KVIzxlOB5//F4JD1+vV7/z9BCcFWgjmDPa37CuE8l5DlXhtgpe91SQQ7YWMPfIykI2kuu+p2c0WiOSVE3lC6DFSXo8VLQuaQIIUgEeh6HQcZhhV7WvQCzbXm9NXiLDEuFpdP0uaRTT/rvBs8kWBOg1e8GrcwuHfYCjyTwXKRk6A01CuDj3m2JXUkCrGyamur2uiVm4DkjQcidCClgBN5b/pYdlp0xEopD4BNakyToxdyWQNfYFFqyu3Xvj0XRJQRsJQEutWcooCa2tjYHsOxqMhMcOWAQMAgYBAwCfpWAnAeivZv15GgooBUBuG6/CSCV9gwFlP6g5aPvNVqpfaG2k60RUWtT+Cbv19gZcu8AdYjBoWYriRDtsOyM3RkmEVhrbd7Dyd5zAGv5PnVbHGrjbEt5YIldVTNBfPLaOwykf64caTYT5HI53XqRIP1yEVcTBfASmNXpu0lQ8OyMmN1Wm2OgdcPSOE0qKjv5jGuHpLVYNVaSLeB4zkUduhURYGVTTjZWiCytEbKGNqtGKBaSWM5TrQAGr8UH6HklBb3PUlyzSgyPPeBczJUiYc6dCOm553ms2WOQ/D8aUrXrEKxCVoJldzEBsbJXlJlXKaoKaTG99SpF0V4s3oqRkFQAVlyhhK0hJ/fhyZq1wmyrNARvFU5kESCFxbGiIwwHq1q81SzRK8nlYimuZPPK5eU1EPdtgk9/X0AJiL0vECVASfjmN0aSBCARFrBPf2com4CxJjgIGAQMAr6x/QPTA1fPoLA3hQAAAABJRU5ErkJggg=='
namedSends = { '0' = ['grad3'] }

[[modules]]
plugin = 'source.file-data-url'
data.url = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABb2lDQ1BpY2MAACiRdZE7SwNBFIW/JErEBym0ELHYIoqFAVEQS42FTZAQFYzaZNdsImTjsrtBxFawsQhYiDa+Cv+BtoKtgiAogoiVP8BXI7LecYUE0Vlm78eZOZeZMxBOlQzLbRgAq+w5mYmkNpud06JPtNBGmCiJnOHaY+l0in/H+w0hVa8Tqtf/+/4cLYt514BQk/CwYTue8KhwasWzFW8KdxjF3KLwvnC/IwcUvlC6HvCj4kLAr4qd6cw4hFVPrVDHeh0bRccS7hOOW6WK8XMedZPWfHlmSmqXzG5cMkyQREOnwhIlPBJSy5LZ376Bb98ky+Ix5G+ziiOOAkXx9otaka55qaboeflKrKrcf+fpmkODQffWJDQ++P5LD0S34LPq+x8Hvv95CJF7OCvX/MuS08ib6NWaFt+D2DqcnNc0fRtON6Dzzs45uW8pIjNsmvB8DG1ZaL+C5vkgq591jm5hek2e6BJ2dqFX9scWvgC2CWfolMhqzAAAAAlwSFlzAAAuIwAALiMBeKU/dgAABJZJREFUeNrtW1mWGyEMVPfjCOL+9wucIc44b5y05dIGTXvmJf3j3XSVSgsCNrrout1ue/S727b9vOq+tgsAM/i4itcNfKdfQci2GLQEyoG/6QoxfQUZ24nAJWhOAtdIkIScSsS2EDgnXAC5ASKhn03EdoLUj8B5tQt8Pp5GRJmwegQ4D7gAHwCyIIS09z/uq4+QsE2AZ0FA1AV4wPeP1m9ACY/30ySUQcmzsDwihBx3ICU2tKz1Z5RQJiTPBnArI2Rc4EGIBrqiGiJDQpmUPCsEVAN0d8BbhLHz+zQJJWAND7wHvBvVHkqFVYw/TEaEhJKo3S3wSOpdSWNIBfJ3rIxtSn+EhBKUvgdeA96d3C7fq4KEx2MDLpfJXioJ5UTwWopqQf+X1m9G5hgh4kdUATPg+4QKquICGhEZEtrdsEgFxfD7EfAzKohYv4MaI1JYVc0VihP1aQB8VAUUANgCBRQbmYe9FFyUak9Gd0qAH1WBtH4PZAdJQnOAs1RBAQBJ5HRU4XngVRV8DH4z/HR0es7ONJs18ovh+6RMdigA/gm4AVr2Am8KGZ71O7jvDoLriwoKsDiBnCulHyWCouARGfcbDVi9KwUVK/HgKQMV0dUhJ8pKoCoRo8ADJLASR6pTVUpF/EAxwJvSWkScCl6QsAUCaFMM2BFxj7qggOBRjcDYQE3fRAv7NPABd9Csy0ptIckiT/7kdWeV6E8rSFAmWN0wECuGrUcCPPCsDPhyMyusbxRMFnCK4tqdL1WnQ4uIoAtV0IxptmvQexzYA2km0qqmC63v9ReaYkB47UYA9AbNTHPPVoF3P2FX2ANf/o5Xj2LZTxigvRlgZvxqEfDdrT507e/w469KwMj0MxRpF1yj47coAd9dDRzFsgtW2iDzl8UPMTHKKAHWDftAKqlKVbW90cqR6tWMAdmqio0Z42rrH8erzrzFfH6fDu+ZH4CewRMpF6oALZVxRvqP53sQOBkDaktkq60fIUJTc5Mu0IwavxkDvABfoQIBngNEaK35F8MW8IHWRrKaJU2QcFpvABCqEVGdJk4nsPmy3J98tpuO7ePqtJqkWiq48amusLC8pz6tcYtU/NRDKAAMix/IhiNbwBERIyQAn9diDRvW78brvwR8qoAUq6N6oAYj9aMD++d/LDIOcvfWJ9DOFWR92DXSlsbMBQTSV2CyltXKU1TMsKMCa8VK9i9h664cg4Jyc+zUA6b1BXE9oCAeVAGSu2l9qQBN7j1YjFDGLYJzDVR0RZbpJRFq47aIfhuKBZmKLGr95nRroipA4LsW+d0dIoNT4agSUH0xowIP/FMcCG+SOtQFIySMWj+jAkqCN1es4Da5QRI0IjS3IKOytLbadiPiQ/DpfYIgHmRcQ06SvJQXUQECTrPgTQKUrJDZ4aVtm49mAQSclBw/BN4lYMIVjkQQ5c8PoWksKmxoBvxvjMHq7arzAmg6rj2qS/Snnhc4phCghm7INrp3L9y9oQUnRtLNiwvODGng0aZLuRtt7ZkhwyU8Imb9n2jRqbH/5wZPalv9mydHHddY4gJf8uxwkAzLBd52evwXnUEn2xgeIeEAAAAASUVORK5CYII='
namedSends = { '0' = ['grad5'] }
